version: '3'

services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
  mongoexpress:
    container_name: mongoexpress
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://mongo:27017
    links: 
      - mongo
  web:
    container_name: web
    build: .
    ports:
      - 9999:80
